apiVersion: v1
baseDomain: goodyspace.com
metadata:
  name: openshift

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3RpbmhhOTAxdm02ZGJzOWRkcW5sN3lqZTR0aWFvZms4dXo6UjVXRlZVMzkyVEFDM0VSNDdGUlpRMFVWMldWTk80MVVVSzU0MVNWWTJMVkpENTdVSVJKNFlRUVhGVUJTOTNONA==","email":"tinha@mail.usf.edu"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3RpbmhhOTAxdm02ZGJzOWRkcW5sN3lqZTR0aWFvZms4dXo6UjVXRlZVMzkyVEFDM0VSNDdGUlpRMFVWMldWTk80MVVVSzU0MVNWWTJMVkpENTdVSVJKNFlRUVhGVUJTOTNONA==","email":"tinha@mail.usf.edu"},"registry.connect.redhat.com":{"auth":"NTI3Mzk4Nnx1aGMtMVZNNmRiUzlkRHFOTDdZSkU0VGlBT2ZLOFV6OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKa1ltUXdZbUk0TlRWaFlUWTBZelJqWWpobE56ZzRaRGd6T0ROaU1tVTVNQ0o5LkdxNUhrWHBJclpQQUtybENrakQzWGxRVElDOUJta0xOUmY3OXRBN28tc3lVZzJ6Z0ZQNlhHTm12V1J2Sm83eDFfT3pjbzBTbnMxQjZRLUxoM3ktWlVwSHBTclVOd3BXbEwxUjhlNXdJWWFFS1lQT3RiTnY5ZjNtVTJnbU1EYW9hSzNQN041cmVQcW9YOGViQTJaS3c5LTJ3VlVWSS1OYl9VbTZvVlZqSGp1RHJ2d3BzV3pURXYzNnEzUU1OZEFSWnFZUVJLQVZ1S0w0blZfTV9lTlFScEhUR2lwSUtpNDI5eEJEZk5WcHJzdmRNWHRFNkxjemdHWHlVUnhtOV8tXy1OQjNQRzlSRkVNRERjbndkVEtwakVjakFCTUhyVFdLNGxhQlNyQUtaUFAxZHhEX1c5WGtrNmZtRjcxTU1md2d1U1JyWGZaTGthZ1hzY21haWNvVnhqNF8xXzBjSFY1UUJvSExtTWsyTFZnTFR2bE4tM0stVHcwLXY0T2NNNFQySC1ySDZhejI5NFV2VXpxNmpkcTJmS1VqdE1ha21DdFVuTXRrams5amtzQW1DSkRoMWp1b1I5cGJwbHJMNVFLZmFJME5mSjY5TU1OV3Y4RFdFSzFIRjAxbGdwYmJ0NVVVSGxtZ09xSU16TE5GVk5qM0M4X2Z4UldyeGlsWXk1Tmk3T2xrOHBUZzE0MmRCalUtd3Z3VXh4X21abTdGUy1fd18xNkZVTF9DOGFNRWktQnh3dGdjWU4wbUVBalluMDZ2b2VNaHd1Mjl1cFRxOXlhSlpLNVpnalpqVUllMmpkbDNWR0xpbWRUUHBJSno5bVNHZ3VyTm9rQm1xUFMtUlpmcl9QcjhXajBORmN4RFhxXzVkMDJEUDlTSzEzaXZQUW1XMHoyWmJxeXRyRHdF","email":"tinha@mail.usf.edu"},"registry.redhat.io":{"auth":"NTI3Mzk4Nnx1aGMtMVZNNmRiUzlkRHFOTDdZSkU0VGlBT2ZLOFV6OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKa1ltUXdZbUk0TlRWaFlUWTBZelJqWWpobE56ZzRaRGd6T0ROaU1tVTVNQ0o5LkdxNUhrWHBJclpQQUtybENrakQzWGxRVElDOUJta0xOUmY3OXRBN28tc3lVZzJ6Z0ZQNlhHTm12V1J2Sm83eDFfT3pjbzBTbnMxQjZRLUxoM3ktWlVwSHBTclVOd3BXbEwxUjhlNXdJWWFFS1lQT3RiTnY5ZjNtVTJnbU1EYW9hSzNQN041cmVQcW9YOGViQTJaS3c5LTJ3VlVWSS1OYl9VbTZvVlZqSGp1RHJ2d3BzV3pURXYzNnEzUU1OZEFSWnFZUVJLQVZ1S0w0blZfTV9lTlFScEhUR2lwSUtpNDI5eEJEZk5WcHJzdmRNWHRFNkxjemdHWHlVUnhtOV8tXy1OQjNQRzlSRkVNRERjbndkVEtwakVjakFCTUhyVFdLNGxhQlNyQUtaUFAxZHhEX1c5WGtrNmZtRjcxTU1md2d1U1JyWGZaTGthZ1hzY21haWNvVnhqNF8xXzBjSFY1UUJvSExtTWsyTFZnTFR2bE4tM0stVHcwLXY0T2NNNFQySC1ySDZhejI5NFV2VXpxNmpkcTJmS1VqdE1ha21DdFVuTXRrams5amtzQW1DSkRoMWp1b1I5cGJwbHJMNVFLZmFJME5mSjY5TU1OV3Y4RFdFSzFIRjAxbGdwYmJ0NVVVSGxtZ09xSU16TE5GVk5qM0M4X2Z4UldyeGlsWXk1Tmk3T2xrOHBUZzE0MmRCalUtd3Z3VXh4X21abTdGUy1fd18xNkZVTF9DOGFNRWktQnh3dGdjWU4wbUVBalluMDZ2b2VNaHd1Mjl1cFRxOXlhSlpLNVpnalpqVUllMmpkbDNWR0xpbWRUUHBJSno5bVNHZ3VyTm9rQm1xUFMtUlpmcl9QcjhXajBORmN4RFhxXzVkMDJEUDlTSzEzaXZQUW1XMHoyWmJxeXRyRHdF","email":"tinha@mail.usf.edu"}}}' 
sshKey: 'ssh-ed25519 AAAA...'   
